services:
  - type: web
    name: task-manager
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"  # Replace 'app' with your main file name without .py
    region: oregon
    plan: free